#!/bin/bash

. /etc/os-release

if [[ $ID == "centos" ]]; then
    yum install --assumeyes epel-release
    yum install --assumeyes python34 python34-setuptools
    ln -s /usr/bin/python3.4 /usr/bin/python3
fi

python3 $CHARM_DIR/hooks/installpy

